apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: huddlehub-dev
build:
  artifacts:
    - image: sergeyarenzon/huddlehub-auth
      context: services/auth
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.json"
            dest: .
    - image: sergeyarenzon/huddlehub-profile
      context: services/profile
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.json"
            dest: .
    - image: sergeyarenzon/huddlehub-tour
      context: services/tour
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.json"
            dest: .
    - image: sergeyarenzon/huddlehub-booking
      context: services/booking
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
          - src: "src/**/*.json"
            dest: .
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
manifests:
  helm:
    releases:
      - name: gateway
        chartPath: k8s/helm/gateway/
        valuesFiles:
          - k8s/helm/gateway/values.yaml
      - name: ingress-nginx
        chartPath: k8s/helm/ingress-nginx/
        valuesFiles:
          - k8s/helm/ingress-nginx/values.yaml
      - name: secrets
        chartPath: k8s/helm/secrets/
        valuesFiles:
          - k8s/helm/secrets/values.yaml
      - name: auth-db
        chartPath: k8s/helm/auth-db/
        valuesFiles:
          - k8s/helm/auth-db/values.yaml
      - name: profile-db
        chartPath: k8s/helm/profile-db/
        valuesFiles:
          - k8s/helm/profile-db/values.yaml
      # - name: tour-db
      #   chartPath: k8s/helm/tour-db/
      #   valuesFiles:
      #     - k8s/helm/tour-db/values.yaml
      # - name: booking-db
      #   chartPath: k8s/helm/booking-db/
      #   valuesFiles:
      #     - k8s/helm/booking-db/values.yaml
      - name: auth
        chartPath: k8s/helm/auth/
        valuesFiles:
          - k8s/helm/auth/values.yaml
      - name: profile
        chartPath: k8s/helm/profile/
        valuesFiles:
          - k8s/helm/profile/values.yaml
      # - name: tour
      #   chartPath: k8s/helm/tour/
      #   valuesFiles:
      #     - k8s/helm/tour/values.yaml
      # - name: booking
      #   chartPath: k8s/helm/booking/
      #   valuesFiles:
      #     - k8s/helm/booking/values.yaml
      # - name: redis
      #   repo: https://charts.bitnami.com/bitnami
      #   remoteChart: redis
      #   valuesFiles:
      #     - k8s/helm/redis/values.yaml

  hooks:
    before:
      # Create global-secrets from k8s/helm/secrets/.env
      - host:
          command: ["sh", "-c", "if [ -f k8s/helm/secrets/.env ]; then kubectl create secret generic global-secrets --from-env-file=k8s/helm/secrets/.env --dry-run=client -o yaml | kubectl apply -f -; else echo 'Warning: k8s/helm/secrets/.env not found - global-secrets will not be created'; fi"]
      # Create auth-secrets from k8s/helm/auth/templates/.env
      - host:
          command: ["sh", "-c", "if [ -f k8s/helm/auth/templates/.env ]; then kubectl create secret generic auth-secrets --from-env-file=k8s/helm/auth/templates/.env --dry-run=client -o yaml | kubectl apply -f -; else echo 'Warning: k8s/helm/auth/templates/.env not found - auth-secrets will not be created'; fi"]
