
# POST http://localhost:4002
# Content-Type: application/json

# {
#   "firs_name": "xsdfx1xasdx2sssdfsdfdfdfsdf3",
#   "last_name": "Arens1dfzon22sdfsdfsdf13",
#   "email": "asa2123s1sdfdf22@sdfsdfgmail.com",
#   "image_url": "http://www.go1ogl12sdfsdfsdf3e222.com"
#  }


# GET http://localhost:4002
# Content-Type: application/json




# GET http://huddlehub.io/api/user/languages
# Content-Type: application/json



# GET http://huddlehub.io/api/tour/category
# curl 'http://huddlehub.io/api/user/languages' \
#   -H 'Accept: application/json, text/plain, */*' \
#   -H 'Accept-Language: en,ru;q=0.9,he;q=0.8' \
#   -H 'Cache-Control: no-cache' \
#   -H 'Connection: keep-alive' \
#   -H 'Origin: http://localhost:3000' \
#   -H 'Pragma: no-cache' \
#   -H 'Referer: http://localhost:3000/' \
#   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'



# POST http://huddlehub.io/api/v1/user/guide
# Content-Type: application/json
# cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkX2F0IjoiMjAyNS0wNy0yOFQxNzozNzo1Ny44ODVaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMjhUMTc6Mzc6NTcuODg1WiIsImZpcnN0X25hbWUiOiJTZXJnZXkiLCJsYXN0X25hbWUiOiJBcmVuem9uIiwiZW1haWwiOiJzZXJnZXlyMTk5MUBnbWFpbC5jb20iLCJpbWFnZV91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMV2xXYVF2RjZBbjdtLTgzQVJZeEQzcUU4RTFrYjRPTy1XbjR5YzJkeG1SQmgwdWEwcT1zOTYtYyIsImd1aWRlIjpudWxsLCJpZCI6IjE2YWE4NTQ3LTU1NzAtNGMwNS04MzE5LWJmMjg2YzI3YzI3YiIsImlhdCI6MTc1NDE2MTI2MCwiZXhwIjoxNzU0MTY0ODYwfQ.j8nY9_akoFmyP-a5OAyMllkk2fytUfCHqoFCOlO0k3Y

# {
#   "name": "Sergey the Guide",
#   "subcategories_id": ["c5b33001-f691-4d94-831a-8d44185e5a53","7bcdf597-0d4b-4c50-921b-f1a68a52ca9e","07a8a248-b1d9-496b-9bf4-637f0c7e20e6","17286200-9242-46d7-b24e-f43fc32cfa67","ead865fd-5d64-437b-8f83-9b85e33a42b5","8857b97d-9238-4f1e-900b-2c26e624eef6","a8844f2d-895e-4dfe-a80c-39b8f486287f","cb39c37c-d9fb-43e6-b08a-5e1521bba108","408d5024-af60-45e3-a46f-5ba7cc993814"],
#   "languages_code": ["he","ru","en"],
#   "country_code": "IL",
#   "city_id": 22,
#   "bio": "Best guide in jerusalem!"
# }

GET http://huddlehub.io/api/v1/user/guide/950108e0-1acd-4860-b02d-fb23e125c152
Content-Type: application/json
cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkNmQxMDA0LTQwMGMtNDU4YS04NzQ4LTAyYmYyMDI4YjU2ZSIsImNyZWF0ZWRfYXQiOiIyMDI1LTA4LTAzVDE0OjU2OjMxLjUxN1oiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wOC0wM1QxNDo1NjozMS41MTdaIiwiZmlyc3RfbmFtZSI6IlNlcmdleSIsImxhc3RfbmFtZSI6IkFyZW56b24iLCJlbWFpbCI6ImFyZW56b25zZXJnZXlAZ21haWwuY29tIiwiaW1hZ2VfdXJsIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUNnOG9jSlpsZnloR2NHY1o5RmVUU1VYcWlaZkRYdXhKWVpJT1ZKVUZmNTBzRWZIc2NrUXdqMD1zOTYtYyIsImd1aWRlIjp7ImlkIjoiYTQxNjIwZmEtZjI2Zi00MjI1LWEzMmMtNDkzMjk1NjBkODM2IiwiY3JlYXRlZF9hdCI6IjIwMjUtMDgtMDNUMTQ6NTY6NTYuMjU0WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA4LTAzVDE0OjU2OjU2LjI1NFoiLCJuYW1lIjoic2Rmc2Rmc2Rmc2RmIiwiYmlvIjoic2Rmc2Rmc2Rmc2Rmc2Rmc2RmIiwiY291bnRyeSI6IkpQIiwiY2l0eSI6MzAsInVzZXIiOiI0ZDZkMTAwNC00MDBjLTQ1OGEtODc0OC0wMmJmMjAyOGI1NmUifSwiaWF0IjoxNzU0MjM4MjY1LCJleHAiOjE3NTQyNDE4NjV9.xBn95CojsjJIee1FwsLwgelffQKTSr0RjRmok0IBloY
