
# POST http://localhost:4002
# Content-Type: application/json

# {
#   "firs_name": "xsdfx1xasdx2sssdfsdfdfdfsdf3",
#   "last_name": "Arens1dfzon22sdfsdfsdf13",
#   "email": "asa2123s1sdfdf22@sdfsdfgmail.com",
#   "image_url": "http://www.go1ogl12sdfsdfsdf3e222.com"
#  }


# GET http://localhost:4002
# Content-Type: application/json




# GET http://huddlehub.io/api/user/languages
# Content-Type: application/json



# GET http://huddlehub.io/api/tour/category
# curl 'http://huddlehub.io/api/user/languages' \
#   -H 'Accept: application/json, text/plain, */*' \
#   -H 'Accept-Language: en,ru;q=0.9,he;q=0.8' \
#   -H 'Cache-Control: no-cache' \
#   -H 'Connection: keep-alive' \
#   -H 'Origin: http://localhost:3000' \
#   -H 'Pragma: no-cache' \
#   -H 'Referer: http://localhost:3000/' \
#   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36'



# POST http://huddlehub.io/api/v1/user/guide
# Content-Type: application/json
# cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkX2F0IjoiMjAyNS0wNy0yOFQxNzozNzo1Ny44ODVaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMjhUMTc6Mzc6NTcuODg1WiIsImZpcnN0X25hbWUiOiJTZXJnZXkiLCJsYXN0X25hbWUiOiJBcmVuem9uIiwiZW1haWwiOiJzZXJnZXlyMTk5MUBnbWFpbC5jb20iLCJpbWFnZV91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMV2xXYVF2RjZBbjdtLTgzQVJZeEQzcUU4RTFrYjRPTy1XbjR5YzJkeG1SQmgwdWEwcT1zOTYtYyIsImd1aWRlIjpudWxsLCJpZCI6IjE2YWE4NTQ3LTU1NzAtNGMwNS04MzE5LWJmMjg2YzI3YzI3YiIsImlhdCI6MTc1NDE2MTI2MCwiZXhwIjoxNzU0MTY0ODYwfQ.j8nY9_akoFmyP-a5OAyMllkk2fytUfCHqoFCOlO0k3Y

# {
#   "name": "Sergey the Guide",
#   "subcategories_id": ["c5b33001-f691-4d94-831a-8d44185e5a53","7bcdf597-0d4b-4c50-921b-f1a68a52ca9e","07a8a248-b1d9-496b-9bf4-637f0c7e20e6","17286200-9242-46d7-b24e-f43fc32cfa67","ead865fd-5d64-437b-8f83-9b85e33a42b5","8857b97d-9238-4f1e-900b-2c26e624eef6","a8844f2d-895e-4dfe-a80c-39b8f486287f","cb39c37c-d9fb-43e6-b08a-5e1521bba108","408d5024-af60-45e3-a46f-5ba7cc993814"],
#   "languages_code": ["he","ru","en"],
#   "country_code": "IL",
#   "city_id": 22,
#   "bio": "Best guide in jerusalem!"
# }

# GET http://huddlehub.io/api/v1/user/16aa8547-5570-4c05-8319-bf286c27c27b/guide
# Content-Type: application/json
# cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2YWE4NTQ3LTU1NzAtNGMwNS04MzE5LWJmMjg2YzI3YzI3YiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA3LTI4VDE3OjM3OjU3Ljg4NVoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wNy0yOFQxNzozNzo1Ny44ODVaIiwiZmlyc3RfbmFtZSI6IlNlcmdleSIsImxhc3RfbmFtZSI6IkFyZW56b24iLCJlbWFpbCI6InNlcmdleXIxOTkxQGdtYWlsLmNvbSIsImltYWdlX3VybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xXbFdhUXZGNkFuN20tODNBUll4RDNxRThFMWtiNE9PLVduNHljMmR4bVJCaDB1YTBxPXM5Ni1jIiwiZ3VpZGUiOiI5NTAxMDhlMC0xYWNkLTQ4NjAtYjAyZC1mYjIzZTEyNWMxNTIiLCJpYXQiOjE3NTQyNDQzOTQsImV4cCI6MTc1NDI0Nzk5NH0.x-c4W7_GDXlNv05f1667thMOiw109qUL-naBL15eNk8



# GET http://huddlehub.io/api/v1/auth/test
# Content-Type: application/json
# cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE2YWE4NTQ3LTU1NzAtNGMwNS04MzE5LWJmMjg2YzI3YzI3YiIsImNyZWF0ZWRfYXQiOiIyMDI1LTA3LTI4VDE3OjM3OjU3Ljg4NVoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wNy0yOFQxNzozNzo1Ny44ODVaIiwiZmlyc3RfbmFtZSI6IlNlcmdleSIsImxhc3RfbmFtZSI6IkFyZW56b24iLCJlbWFpbCI6InNlcmdleXIxOTkxQGdtYWlsLmNvbSIsImltYWdlX3VybCI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0xXbFdhUXZGNkFuN20tODNBUll4RDNxRThFMWtiNE9PLVduNHljMmR4bVJCaDB1YTBxPXM5Ni1jIiwiZ3VpZGUiOiI5NTAxMDhlMC0xYWNkLTQ4NjAtYjAyZC1mYjIzZTEyNWMxNTIiLCJpYXQiOjE3NTQyNDQzOTQsImV4cCI6MTc1NDI0Nzk5NH0.x-c4W7_GDXlNv05f1667thMOiw109qUL-naBL15eNk8



# POST http://huddlehub.io/api/v1/auth/refresh
# Content-Type: application/json
# cookie: refreshToken=ccd9274b-0755-4fe4-8b8e-cf42259c7ff1
# cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTdiZGI5Ny1iMGFiLTQ2ZTctYjNkMC1iNzNkOWM2Y2ZiYzMiLCJpc3MiOiJhdXRoIiwiYXVkIjoiY2xpZW50Iiwicm9sZXMiOlsiY2xpZW50Il0sInNjb3BlcyI6WyJ1c2VyOnJlYWQiLCJ1c2VyOndyaXRlIl0sImlhdCI6MTc1NjgzMzI2ODEyNiwiZXhwIjoxNzU2ODMzMjY5MDI2fQ.5LtOCitspMevigKYqXPYPmD1UcYdkzDceZ6qYRqT0fU


GET http://localhost/api/v1/tour/tour
Content-Type: "application/json"
Authorization: "Bearer eyJhbGciOiJFZERTQSIsImtpZCI6IjAxOWFiNzIwLTE2YjgtNzdlMy04ZjE4LTE0NGM4M2FlZTk3YSJ9.eyJpYXQiOjE3NjQwMDk4NjUsImlzcyI6ImF1dGgtc3ZjIiwiYXVkIjpbInByb2ZpbGUtc3ZjIiwidG91ci1zdmMiXSwiaWQiOiIwMTlhYjcyMC0xMmViLTcxMjgtYWRhYy04YjBlY2ZkODk1NmIiLCJzdWIiOiIwMTlhYjcyMC0xMmViLTcxMjgtYWRhYy04YjBlY2ZkODk1NmIiLCJlbWFpbCI6InNlcmdleXIxOTkxQGdtYWlsLmNvbSIsInJvbGVzIjpbXSwic2NvcGVzIjpbXSwiZXhwIjoxNzY0NjE0NjY1LCJuYmYiOjE3NjQwMDk4NjUsImp0aSI6IktCdTN2d005SGtBTTRlaFYwWkpmd3RPaDNVSHZvMVRyIn0.AWxBSos-8lofP-dw7EfSQeIkfOAw9hIkJAMPCElK85E98vl6EB5YottlBcpwklxnjUsJ7knj6Pk9mBqVfZAcDw"
