FROM node:24-alpine AS base
RUN npm install -g pnpm

FROM base AS build
WORKDIR /app
COPY . .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm --filter "@rapid-guide-io/*" build
RUN pnpm deploy --filter=user --legacy /deploy/user

FROM base
COPY --from=build /deploy/user /app/services/user
WORKDIR /app/services/user
EXPOSE 3000
CMD ["pnpm", "run", "start:dev"]
