/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedSigninRouteImport } from './routes/_unauthenticated/signin'
import { Route as AuthenticatedTravellerRouteImport } from './routes/_authenticated/traveller'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as UnauthenticatedSignupIndexRouteImport } from './routes/_unauthenticated/signup/index'
import { Route as AuthenticatedTravellerIndexRouteImport } from './routes/_authenticated/traveller/index'
import { Route as AuthenticatedGuideIndexRouteImport } from './routes/_authenticated/guide/index'
import { Route as UnauthenticatedSignupTravellerRouteImport } from './routes/_unauthenticated/signup/traveller'
import { Route as UnauthenticatedSignupGuideRouteImport } from './routes/_unauthenticated/signup/guide'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSigninRoute = UnauthenticatedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedTravellerRoute = AuthenticatedTravellerRouteImport.update({
  id: '/traveller',
  path: '/traveller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignupIndexRoute =
  UnauthenticatedSignupIndexRouteImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedTravellerIndexRoute =
  AuthenticatedTravellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravellerRoute,
  } as any)
const AuthenticatedGuideIndexRoute = AuthenticatedGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGuideRoute,
} as any)
const UnauthenticatedSignupTravellerRoute =
  UnauthenticatedSignupTravellerRouteImport.update({
    id: '/signup/traveller',
    path: '/signup/traveller',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignupGuideRoute =
  UnauthenticatedSignupGuideRouteImport.update({
    id: '/signup/guide',
    path: '/signup/guide',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/traveller': typeof AuthenticatedTravellerRouteWithChildren
  '/signin': typeof UnauthenticatedSigninRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/guide/': typeof AuthenticatedGuideIndexRoute
  '/traveller/': typeof AuthenticatedTravellerIndexRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/guide': typeof AuthenticatedGuideIndexRoute
  '/traveller': typeof AuthenticatedTravellerIndexRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/guide': typeof AuthenticatedGuideRouteWithChildren
  '/_authenticated/traveller': typeof AuthenticatedTravellerRouteWithChildren
  '/_unauthenticated/signin': typeof UnauthenticatedSigninRoute
  '/_unauthenticated/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/_unauthenticated/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/_authenticated/guide/': typeof AuthenticatedGuideIndexRoute
  '/_authenticated/traveller/': typeof AuthenticatedTravellerIndexRoute
  '/_unauthenticated/signup/': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/traveller'
    | '/signin'
    | '/signup/guide'
    | '/signup/traveller'
    | '/guide/'
    | '/traveller/'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup/guide'
    | '/signup/traveller'
    | '/guide'
    | '/traveller'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/guide'
    | '/_authenticated/traveller'
    | '/_unauthenticated/signin'
    | '/_unauthenticated/signup/guide'
    | '/_unauthenticated/signup/traveller'
    | '/_authenticated/guide/'
    | '/_authenticated/traveller/'
    | '/_unauthenticated/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/signin': {
      id: '/_unauthenticated/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof UnauthenticatedSigninRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/traveller': {
      id: '/_authenticated/traveller'
      path: '/traveller'
      fullPath: '/traveller'
      preLoaderRoute: typeof AuthenticatedTravellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/signup/': {
      id: '/_unauthenticated/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/traveller/': {
      id: '/_authenticated/traveller/'
      path: '/'
      fullPath: '/traveller/'
      preLoaderRoute: typeof AuthenticatedTravellerIndexRouteImport
      parentRoute: typeof AuthenticatedTravellerRoute
    }
    '/_authenticated/guide/': {
      id: '/_authenticated/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof AuthenticatedGuideIndexRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_unauthenticated/signup/traveller': {
      id: '/_unauthenticated/signup/traveller'
      path: '/signup/traveller'
      fullPath: '/signup/traveller'
      preLoaderRoute: typeof UnauthenticatedSignupTravellerRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup/guide': {
      id: '/_unauthenticated/signup/guide'
      path: '/signup/guide'
      fullPath: '/signup/guide'
      preLoaderRoute: typeof UnauthenticatedSignupGuideRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
  }
}

interface AuthenticatedGuideRouteChildren {
  AuthenticatedGuideIndexRoute: typeof AuthenticatedGuideIndexRoute
}

const AuthenticatedGuideRouteChildren: AuthenticatedGuideRouteChildren = {
  AuthenticatedGuideIndexRoute: AuthenticatedGuideIndexRoute,
}

const AuthenticatedGuideRouteWithChildren =
  AuthenticatedGuideRoute._addFileChildren(AuthenticatedGuideRouteChildren)

interface AuthenticatedTravellerRouteChildren {
  AuthenticatedTravellerIndexRoute: typeof AuthenticatedTravellerIndexRoute
}

const AuthenticatedTravellerRouteChildren: AuthenticatedTravellerRouteChildren =
  {
    AuthenticatedTravellerIndexRoute: AuthenticatedTravellerIndexRoute,
  }

const AuthenticatedTravellerRouteWithChildren =
  AuthenticatedTravellerRoute._addFileChildren(
    AuthenticatedTravellerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRouteWithChildren
  AuthenticatedTravellerRoute: typeof AuthenticatedTravellerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGuideRoute: AuthenticatedGuideRouteWithChildren,
  AuthenticatedTravellerRoute: AuthenticatedTravellerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedSigninRoute: typeof UnauthenticatedSigninRoute
  UnauthenticatedSignupGuideRoute: typeof UnauthenticatedSignupGuideRoute
  UnauthenticatedSignupTravellerRoute: typeof UnauthenticatedSignupTravellerRoute
  UnauthenticatedSignupIndexRoute: typeof UnauthenticatedSignupIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSigninRoute: UnauthenticatedSigninRoute,
  UnauthenticatedSignupGuideRoute: UnauthenticatedSignupGuideRoute,
  UnauthenticatedSignupTravellerRoute: UnauthenticatedSignupTravellerRoute,
  UnauthenticatedSignupIndexRoute: UnauthenticatedSignupIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
