/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedSigninRouteImport } from './routes/_unauthenticated/signin'
import { Route as AuthenticatedTravellerRouteImport } from './routes/_authenticated/traveller'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as UnauthenticatedSignupIndexRouteImport } from './routes/_unauthenticated/signup/index'
import { Route as AuthenticatedTravellerIndexRouteImport } from './routes/_authenticated/traveller/index'
import { Route as AuthenticatedGuideIndexRouteImport } from './routes/_authenticated/guide/index'
import { Route as AuthenticatedTravellerToursRouteImport } from './routes/_authenticated/traveller/tours'
import { Route as AuthenticatedGuideToursRouteImport } from './routes/_authenticated/guide/tours'
import { Route as AuthenticatedGuidePreferencesRouteImport } from './routes/_authenticated/guide/preferences'
import { Route as UnauthenticatedSignupTravellerIndexRouteImport } from './routes/_unauthenticated/signup/traveller/index'
import { Route as UnauthenticatedSignupGuideIndexRouteImport } from './routes/_unauthenticated/signup/guide/index'
import { Route as AuthenticatedTravellerToursIndexRouteImport } from './routes/_authenticated/traveller/tours/index'
import { Route as AuthenticatedGuideToursIndexRouteImport } from './routes/_authenticated/guide/tours/index'
import { Route as AuthenticatedGuideCalendarIndexRouteImport } from './routes/_authenticated/guide/calendar/index'
import { Route as AuthenticatedTravellerToursTourIdRouteImport } from './routes/_authenticated/traveller/tours/$tourId'
import { Route as AuthenticatedGuideToursTourIdRouteImport } from './routes/_authenticated/guide/tours/$tourId'
import { Route as AuthenticatedTravellerToursTourIdIndexRouteImport } from './routes/_authenticated/traveller/tours/$tourId/index'
import { Route as AuthenticatedGuideToursNewIndexRouteImport } from './routes/_authenticated/guide/tours/new/index'
import { Route as AuthenticatedGuideToursTourIdIndexRouteImport } from './routes/_authenticated/guide/tours/$tourId/index'
import { Route as AuthenticatedTravellerToursTourIdReservationIndexRouteImport } from './routes/_authenticated/traveller/tours/$tourId/reservation/index'
import { Route as AuthenticatedGuideToursTourIdEditIndexRouteImport } from './routes/_authenticated/guide/tours/$tourId/edit/index'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSigninRoute = UnauthenticatedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedTravellerRoute = AuthenticatedTravellerRouteImport.update({
  id: '/traveller',
  path: '/traveller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignupIndexRoute =
  UnauthenticatedSignupIndexRouteImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedTravellerIndexRoute =
  AuthenticatedTravellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravellerRoute,
  } as any)
const AuthenticatedGuideIndexRoute = AuthenticatedGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGuideRoute,
} as any)
const AuthenticatedTravellerToursRoute =
  AuthenticatedTravellerToursRouteImport.update({
    id: '/tours',
    path: '/tours',
    getParentRoute: () => AuthenticatedTravellerRoute,
  } as any)
const AuthenticatedGuideToursRoute = AuthenticatedGuideToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AuthenticatedGuideRoute,
} as any)
const AuthenticatedGuidePreferencesRoute =
  AuthenticatedGuidePreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const UnauthenticatedSignupTravellerIndexRoute =
  UnauthenticatedSignupTravellerIndexRouteImport.update({
    id: '/signup/traveller/',
    path: '/signup/traveller/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignupGuideIndexRoute =
  UnauthenticatedSignupGuideIndexRouteImport.update({
    id: '/signup/guide/',
    path: '/signup/guide/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const AuthenticatedTravellerToursIndexRoute =
  AuthenticatedTravellerToursIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravellerToursRoute,
  } as any)
const AuthenticatedGuideToursIndexRoute =
  AuthenticatedGuideToursIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGuideToursRoute,
  } as any)
const AuthenticatedGuideCalendarIndexRoute =
  AuthenticatedGuideCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedGuideRoute,
  } as any)
const AuthenticatedTravellerToursTourIdRoute =
  AuthenticatedTravellerToursTourIdRouteImport.update({
    id: '/$tourId',
    path: '/$tourId',
    getParentRoute: () => AuthenticatedTravellerToursRoute,
  } as any)
const AuthenticatedGuideToursTourIdRoute =
  AuthenticatedGuideToursTourIdRouteImport.update({
    id: '/$tourId',
    path: '/$tourId',
    getParentRoute: () => AuthenticatedGuideToursRoute,
  } as any)
const AuthenticatedTravellerToursTourIdIndexRoute =
  AuthenticatedTravellerToursTourIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTravellerToursTourIdRoute,
  } as any)
const AuthenticatedGuideToursNewIndexRoute =
  AuthenticatedGuideToursNewIndexRouteImport.update({
    id: '/new/',
    path: '/new/',
    getParentRoute: () => AuthenticatedGuideToursRoute,
  } as any)
const AuthenticatedGuideToursTourIdIndexRoute =
  AuthenticatedGuideToursTourIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGuideToursTourIdRoute,
  } as any)
const AuthenticatedTravellerToursTourIdReservationIndexRoute =
  AuthenticatedTravellerToursTourIdReservationIndexRouteImport.update({
    id: '/reservation/',
    path: '/reservation/',
    getParentRoute: () => AuthenticatedTravellerToursTourIdRoute,
  } as any)
const AuthenticatedGuideToursTourIdEditIndexRoute =
  AuthenticatedGuideToursTourIdEditIndexRouteImport.update({
    id: '/edit/',
    path: '/edit/',
    getParentRoute: () => AuthenticatedGuideToursTourIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof AuthenticatedGuideRouteWithChildren
  '/traveller': typeof AuthenticatedTravellerRouteWithChildren
  '/signin': typeof UnauthenticatedSigninRoute
  '/guide/preferences': typeof AuthenticatedGuidePreferencesRoute
  '/guide/tours': typeof AuthenticatedGuideToursRouteWithChildren
  '/traveller/tours': typeof AuthenticatedTravellerToursRouteWithChildren
  '/guide/': typeof AuthenticatedGuideIndexRoute
  '/traveller/': typeof AuthenticatedTravellerIndexRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
  '/guide/tours/$tourId': typeof AuthenticatedGuideToursTourIdRouteWithChildren
  '/traveller/tours/$tourId': typeof AuthenticatedTravellerToursTourIdRouteWithChildren
  '/guide/calendar': typeof AuthenticatedGuideCalendarIndexRoute
  '/guide/tours/': typeof AuthenticatedGuideToursIndexRoute
  '/traveller/tours/': typeof AuthenticatedTravellerToursIndexRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideIndexRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerIndexRoute
  '/guide/tours/$tourId/': typeof AuthenticatedGuideToursTourIdIndexRoute
  '/guide/tours/new': typeof AuthenticatedGuideToursNewIndexRoute
  '/traveller/tours/$tourId/': typeof AuthenticatedTravellerToursTourIdIndexRoute
  '/guide/tours/$tourId/edit': typeof AuthenticatedGuideToursTourIdEditIndexRoute
  '/traveller/tours/$tourId/reservation': typeof AuthenticatedTravellerToursTourIdReservationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/guide/preferences': typeof AuthenticatedGuidePreferencesRoute
  '/guide': typeof AuthenticatedGuideIndexRoute
  '/traveller': typeof AuthenticatedTravellerIndexRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
  '/guide/calendar': typeof AuthenticatedGuideCalendarIndexRoute
  '/guide/tours': typeof AuthenticatedGuideToursIndexRoute
  '/traveller/tours': typeof AuthenticatedTravellerToursIndexRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideIndexRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerIndexRoute
  '/guide/tours/$tourId': typeof AuthenticatedGuideToursTourIdIndexRoute
  '/guide/tours/new': typeof AuthenticatedGuideToursNewIndexRoute
  '/traveller/tours/$tourId': typeof AuthenticatedTravellerToursTourIdIndexRoute
  '/guide/tours/$tourId/edit': typeof AuthenticatedGuideToursTourIdEditIndexRoute
  '/traveller/tours/$tourId/reservation': typeof AuthenticatedTravellerToursTourIdReservationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/guide': typeof AuthenticatedGuideRouteWithChildren
  '/_authenticated/traveller': typeof AuthenticatedTravellerRouteWithChildren
  '/_unauthenticated/signin': typeof UnauthenticatedSigninRoute
  '/_authenticated/guide/preferences': typeof AuthenticatedGuidePreferencesRoute
  '/_authenticated/guide/tours': typeof AuthenticatedGuideToursRouteWithChildren
  '/_authenticated/traveller/tours': typeof AuthenticatedTravellerToursRouteWithChildren
  '/_authenticated/guide/': typeof AuthenticatedGuideIndexRoute
  '/_authenticated/traveller/': typeof AuthenticatedTravellerIndexRoute
  '/_unauthenticated/signup/': typeof UnauthenticatedSignupIndexRoute
  '/_authenticated/guide/tours/$tourId': typeof AuthenticatedGuideToursTourIdRouteWithChildren
  '/_authenticated/traveller/tours/$tourId': typeof AuthenticatedTravellerToursTourIdRouteWithChildren
  '/_authenticated/guide/calendar/': typeof AuthenticatedGuideCalendarIndexRoute
  '/_authenticated/guide/tours/': typeof AuthenticatedGuideToursIndexRoute
  '/_authenticated/traveller/tours/': typeof AuthenticatedTravellerToursIndexRoute
  '/_unauthenticated/signup/guide/': typeof UnauthenticatedSignupGuideIndexRoute
  '/_unauthenticated/signup/traveller/': typeof UnauthenticatedSignupTravellerIndexRoute
  '/_authenticated/guide/tours/$tourId/': typeof AuthenticatedGuideToursTourIdIndexRoute
  '/_authenticated/guide/tours/new/': typeof AuthenticatedGuideToursNewIndexRoute
  '/_authenticated/traveller/tours/$tourId/': typeof AuthenticatedTravellerToursTourIdIndexRoute
  '/_authenticated/guide/tours/$tourId/edit/': typeof AuthenticatedGuideToursTourIdEditIndexRoute
  '/_authenticated/traveller/tours/$tourId/reservation/': typeof AuthenticatedTravellerToursTourIdReservationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/traveller'
    | '/signin'
    | '/guide/preferences'
    | '/guide/tours'
    | '/traveller/tours'
    | '/guide/'
    | '/traveller/'
    | '/signup'
    | '/guide/tours/$tourId'
    | '/traveller/tours/$tourId'
    | '/guide/calendar'
    | '/guide/tours/'
    | '/traveller/tours/'
    | '/signup/guide'
    | '/signup/traveller'
    | '/guide/tours/$tourId/'
    | '/guide/tours/new'
    | '/traveller/tours/$tourId/'
    | '/guide/tours/$tourId/edit'
    | '/traveller/tours/$tourId/reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/guide/preferences'
    | '/guide'
    | '/traveller'
    | '/signup'
    | '/guide/calendar'
    | '/guide/tours'
    | '/traveller/tours'
    | '/signup/guide'
    | '/signup/traveller'
    | '/guide/tours/$tourId'
    | '/guide/tours/new'
    | '/traveller/tours/$tourId'
    | '/guide/tours/$tourId/edit'
    | '/traveller/tours/$tourId/reservation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/guide'
    | '/_authenticated/traveller'
    | '/_unauthenticated/signin'
    | '/_authenticated/guide/preferences'
    | '/_authenticated/guide/tours'
    | '/_authenticated/traveller/tours'
    | '/_authenticated/guide/'
    | '/_authenticated/traveller/'
    | '/_unauthenticated/signup/'
    | '/_authenticated/guide/tours/$tourId'
    | '/_authenticated/traveller/tours/$tourId'
    | '/_authenticated/guide/calendar/'
    | '/_authenticated/guide/tours/'
    | '/_authenticated/traveller/tours/'
    | '/_unauthenticated/signup/guide/'
    | '/_unauthenticated/signup/traveller/'
    | '/_authenticated/guide/tours/$tourId/'
    | '/_authenticated/guide/tours/new/'
    | '/_authenticated/traveller/tours/$tourId/'
    | '/_authenticated/guide/tours/$tourId/edit/'
    | '/_authenticated/traveller/tours/$tourId/reservation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/signin': {
      id: '/_unauthenticated/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof UnauthenticatedSigninRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/traveller': {
      id: '/_authenticated/traveller'
      path: '/traveller'
      fullPath: '/traveller'
      preLoaderRoute: typeof AuthenticatedTravellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/signup/': {
      id: '/_unauthenticated/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/traveller/': {
      id: '/_authenticated/traveller/'
      path: '/'
      fullPath: '/traveller/'
      preLoaderRoute: typeof AuthenticatedTravellerIndexRouteImport
      parentRoute: typeof AuthenticatedTravellerRoute
    }
    '/_authenticated/guide/': {
      id: '/_authenticated/guide/'
      path: '/'
      fullPath: '/guide/'
      preLoaderRoute: typeof AuthenticatedGuideIndexRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/traveller/tours': {
      id: '/_authenticated/traveller/tours'
      path: '/tours'
      fullPath: '/traveller/tours'
      preLoaderRoute: typeof AuthenticatedTravellerToursRouteImport
      parentRoute: typeof AuthenticatedTravellerRoute
    }
    '/_authenticated/guide/tours': {
      id: '/_authenticated/guide/tours'
      path: '/tours'
      fullPath: '/guide/tours'
      preLoaderRoute: typeof AuthenticatedGuideToursRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/guide/preferences': {
      id: '/_authenticated/guide/preferences'
      path: '/preferences'
      fullPath: '/guide/preferences'
      preLoaderRoute: typeof AuthenticatedGuidePreferencesRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_unauthenticated/signup/traveller/': {
      id: '/_unauthenticated/signup/traveller/'
      path: '/signup/traveller'
      fullPath: '/signup/traveller'
      preLoaderRoute: typeof UnauthenticatedSignupTravellerIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup/guide/': {
      id: '/_unauthenticated/signup/guide/'
      path: '/signup/guide'
      fullPath: '/signup/guide'
      preLoaderRoute: typeof UnauthenticatedSignupGuideIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/traveller/tours/': {
      id: '/_authenticated/traveller/tours/'
      path: '/'
      fullPath: '/traveller/tours/'
      preLoaderRoute: typeof AuthenticatedTravellerToursIndexRouteImport
      parentRoute: typeof AuthenticatedTravellerToursRoute
    }
    '/_authenticated/guide/tours/': {
      id: '/_authenticated/guide/tours/'
      path: '/'
      fullPath: '/guide/tours/'
      preLoaderRoute: typeof AuthenticatedGuideToursIndexRouteImport
      parentRoute: typeof AuthenticatedGuideToursRoute
    }
    '/_authenticated/guide/calendar/': {
      id: '/_authenticated/guide/calendar/'
      path: '/calendar'
      fullPath: '/guide/calendar'
      preLoaderRoute: typeof AuthenticatedGuideCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedGuideRoute
    }
    '/_authenticated/traveller/tours/$tourId': {
      id: '/_authenticated/traveller/tours/$tourId'
      path: '/$tourId'
      fullPath: '/traveller/tours/$tourId'
      preLoaderRoute: typeof AuthenticatedTravellerToursTourIdRouteImport
      parentRoute: typeof AuthenticatedTravellerToursRoute
    }
    '/_authenticated/guide/tours/$tourId': {
      id: '/_authenticated/guide/tours/$tourId'
      path: '/$tourId'
      fullPath: '/guide/tours/$tourId'
      preLoaderRoute: typeof AuthenticatedGuideToursTourIdRouteImport
      parentRoute: typeof AuthenticatedGuideToursRoute
    }
    '/_authenticated/traveller/tours/$tourId/': {
      id: '/_authenticated/traveller/tours/$tourId/'
      path: '/'
      fullPath: '/traveller/tours/$tourId/'
      preLoaderRoute: typeof AuthenticatedTravellerToursTourIdIndexRouteImport
      parentRoute: typeof AuthenticatedTravellerToursTourIdRoute
    }
    '/_authenticated/guide/tours/new/': {
      id: '/_authenticated/guide/tours/new/'
      path: '/new'
      fullPath: '/guide/tours/new'
      preLoaderRoute: typeof AuthenticatedGuideToursNewIndexRouteImport
      parentRoute: typeof AuthenticatedGuideToursRoute
    }
    '/_authenticated/guide/tours/$tourId/': {
      id: '/_authenticated/guide/tours/$tourId/'
      path: '/'
      fullPath: '/guide/tours/$tourId/'
      preLoaderRoute: typeof AuthenticatedGuideToursTourIdIndexRouteImport
      parentRoute: typeof AuthenticatedGuideToursTourIdRoute
    }
    '/_authenticated/traveller/tours/$tourId/reservation/': {
      id: '/_authenticated/traveller/tours/$tourId/reservation/'
      path: '/reservation'
      fullPath: '/traveller/tours/$tourId/reservation'
      preLoaderRoute: typeof AuthenticatedTravellerToursTourIdReservationIndexRouteImport
      parentRoute: typeof AuthenticatedTravellerToursTourIdRoute
    }
    '/_authenticated/guide/tours/$tourId/edit/': {
      id: '/_authenticated/guide/tours/$tourId/edit/'
      path: '/edit'
      fullPath: '/guide/tours/$tourId/edit'
      preLoaderRoute: typeof AuthenticatedGuideToursTourIdEditIndexRouteImport
      parentRoute: typeof AuthenticatedGuideToursTourIdRoute
    }
  }
}

interface AuthenticatedGuideToursTourIdRouteChildren {
  AuthenticatedGuideToursTourIdIndexRoute: typeof AuthenticatedGuideToursTourIdIndexRoute
  AuthenticatedGuideToursTourIdEditIndexRoute: typeof AuthenticatedGuideToursTourIdEditIndexRoute
}

const AuthenticatedGuideToursTourIdRouteChildren: AuthenticatedGuideToursTourIdRouteChildren =
  {
    AuthenticatedGuideToursTourIdIndexRoute:
      AuthenticatedGuideToursTourIdIndexRoute,
    AuthenticatedGuideToursTourIdEditIndexRoute:
      AuthenticatedGuideToursTourIdEditIndexRoute,
  }

const AuthenticatedGuideToursTourIdRouteWithChildren =
  AuthenticatedGuideToursTourIdRoute._addFileChildren(
    AuthenticatedGuideToursTourIdRouteChildren,
  )

interface AuthenticatedGuideToursRouteChildren {
  AuthenticatedGuideToursTourIdRoute: typeof AuthenticatedGuideToursTourIdRouteWithChildren
  AuthenticatedGuideToursIndexRoute: typeof AuthenticatedGuideToursIndexRoute
  AuthenticatedGuideToursNewIndexRoute: typeof AuthenticatedGuideToursNewIndexRoute
}

const AuthenticatedGuideToursRouteChildren: AuthenticatedGuideToursRouteChildren =
  {
    AuthenticatedGuideToursTourIdRoute:
      AuthenticatedGuideToursTourIdRouteWithChildren,
    AuthenticatedGuideToursIndexRoute: AuthenticatedGuideToursIndexRoute,
    AuthenticatedGuideToursNewIndexRoute: AuthenticatedGuideToursNewIndexRoute,
  }

const AuthenticatedGuideToursRouteWithChildren =
  AuthenticatedGuideToursRoute._addFileChildren(
    AuthenticatedGuideToursRouteChildren,
  )

interface AuthenticatedGuideRouteChildren {
  AuthenticatedGuidePreferencesRoute: typeof AuthenticatedGuidePreferencesRoute
  AuthenticatedGuideToursRoute: typeof AuthenticatedGuideToursRouteWithChildren
  AuthenticatedGuideIndexRoute: typeof AuthenticatedGuideIndexRoute
  AuthenticatedGuideCalendarIndexRoute: typeof AuthenticatedGuideCalendarIndexRoute
}

const AuthenticatedGuideRouteChildren: AuthenticatedGuideRouteChildren = {
  AuthenticatedGuidePreferencesRoute: AuthenticatedGuidePreferencesRoute,
  AuthenticatedGuideToursRoute: AuthenticatedGuideToursRouteWithChildren,
  AuthenticatedGuideIndexRoute: AuthenticatedGuideIndexRoute,
  AuthenticatedGuideCalendarIndexRoute: AuthenticatedGuideCalendarIndexRoute,
}

const AuthenticatedGuideRouteWithChildren =
  AuthenticatedGuideRoute._addFileChildren(AuthenticatedGuideRouteChildren)

interface AuthenticatedTravellerToursTourIdRouteChildren {
  AuthenticatedTravellerToursTourIdIndexRoute: typeof AuthenticatedTravellerToursTourIdIndexRoute
  AuthenticatedTravellerToursTourIdReservationIndexRoute: typeof AuthenticatedTravellerToursTourIdReservationIndexRoute
}

const AuthenticatedTravellerToursTourIdRouteChildren: AuthenticatedTravellerToursTourIdRouteChildren =
  {
    AuthenticatedTravellerToursTourIdIndexRoute:
      AuthenticatedTravellerToursTourIdIndexRoute,
    AuthenticatedTravellerToursTourIdReservationIndexRoute:
      AuthenticatedTravellerToursTourIdReservationIndexRoute,
  }

const AuthenticatedTravellerToursTourIdRouteWithChildren =
  AuthenticatedTravellerToursTourIdRoute._addFileChildren(
    AuthenticatedTravellerToursTourIdRouteChildren,
  )

interface AuthenticatedTravellerToursRouteChildren {
  AuthenticatedTravellerToursTourIdRoute: typeof AuthenticatedTravellerToursTourIdRouteWithChildren
  AuthenticatedTravellerToursIndexRoute: typeof AuthenticatedTravellerToursIndexRoute
}

const AuthenticatedTravellerToursRouteChildren: AuthenticatedTravellerToursRouteChildren =
  {
    AuthenticatedTravellerToursTourIdRoute:
      AuthenticatedTravellerToursTourIdRouteWithChildren,
    AuthenticatedTravellerToursIndexRoute:
      AuthenticatedTravellerToursIndexRoute,
  }

const AuthenticatedTravellerToursRouteWithChildren =
  AuthenticatedTravellerToursRoute._addFileChildren(
    AuthenticatedTravellerToursRouteChildren,
  )

interface AuthenticatedTravellerRouteChildren {
  AuthenticatedTravellerToursRoute: typeof AuthenticatedTravellerToursRouteWithChildren
  AuthenticatedTravellerIndexRoute: typeof AuthenticatedTravellerIndexRoute
}

const AuthenticatedTravellerRouteChildren: AuthenticatedTravellerRouteChildren =
  {
    AuthenticatedTravellerToursRoute:
      AuthenticatedTravellerToursRouteWithChildren,
    AuthenticatedTravellerIndexRoute: AuthenticatedTravellerIndexRoute,
  }

const AuthenticatedTravellerRouteWithChildren =
  AuthenticatedTravellerRoute._addFileChildren(
    AuthenticatedTravellerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRouteWithChildren
  AuthenticatedTravellerRoute: typeof AuthenticatedTravellerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGuideRoute: AuthenticatedGuideRouteWithChildren,
  AuthenticatedTravellerRoute: AuthenticatedTravellerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedSigninRoute: typeof UnauthenticatedSigninRoute
  UnauthenticatedSignupIndexRoute: typeof UnauthenticatedSignupIndexRoute
  UnauthenticatedSignupGuideIndexRoute: typeof UnauthenticatedSignupGuideIndexRoute
  UnauthenticatedSignupTravellerIndexRoute: typeof UnauthenticatedSignupTravellerIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSigninRoute: UnauthenticatedSigninRoute,
  UnauthenticatedSignupIndexRoute: UnauthenticatedSignupIndexRoute,
  UnauthenticatedSignupGuideIndexRoute: UnauthenticatedSignupGuideIndexRoute,
  UnauthenticatedSignupTravellerIndexRoute:
    UnauthenticatedSignupTravellerIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
