/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthenticatedSigninRouteImport } from './routes/_unauthenticated/signin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as UnauthenticatedSignupIndexRouteImport } from './routes/_unauthenticated/signup/index'
import { Route as UnauthenticatedSignupTravellerRouteImport } from './routes/_unauthenticated/signup/traveller'
import { Route as UnauthenticatedSignupGuideRouteImport } from './routes/_unauthenticated/signup/guide'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedSigninRoute = UnauthenticatedSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => UnauthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const UnauthenticatedSignupIndexRoute =
  UnauthenticatedSignupIndexRouteImport.update({
    id: '/signup/',
    path: '/signup/',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignupTravellerRoute =
  UnauthenticatedSignupTravellerRouteImport.update({
    id: '/signup/traveller',
    path: '/signup/traveller',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)
const UnauthenticatedSignupGuideRoute =
  UnauthenticatedSignupGuideRouteImport.update({
    id: '/signup/guide',
    path: '/signup/guide',
    getParentRoute: () => UnauthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/signin': typeof UnauthenticatedSigninRoute
  '/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/signup': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_unauthenticated/signin': typeof UnauthenticatedSigninRoute
  '/_unauthenticated/signup/guide': typeof UnauthenticatedSignupGuideRoute
  '/_unauthenticated/signup/traveller': typeof UnauthenticatedSignupTravellerRoute
  '/_unauthenticated/signup/': typeof UnauthenticatedSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup/guide'
    | '/signup/traveller'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/signin'
    | '/signup/guide'
    | '/signup/traveller'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_unauthenticated'
    | '/_authenticated/dashboard'
    | '/_unauthenticated/signin'
    | '/_unauthenticated/signup/guide'
    | '/_unauthenticated/signup/traveller'
    | '/_unauthenticated/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/signin': {
      id: '/_unauthenticated/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof UnauthenticatedSigninRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_unauthenticated/signup/': {
      id: '/_unauthenticated/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthenticatedSignupIndexRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup/traveller': {
      id: '/_unauthenticated/signup/traveller'
      path: '/signup/traveller'
      fullPath: '/signup/traveller'
      preLoaderRoute: typeof UnauthenticatedSignupTravellerRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/_unauthenticated/signup/guide': {
      id: '/_unauthenticated/signup/guide'
      path: '/signup/guide'
      fullPath: '/signup/guide'
      preLoaderRoute: typeof UnauthenticatedSignupGuideRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface UnauthenticatedRouteChildren {
  UnauthenticatedSigninRoute: typeof UnauthenticatedSigninRoute
  UnauthenticatedSignupGuideRoute: typeof UnauthenticatedSignupGuideRoute
  UnauthenticatedSignupTravellerRoute: typeof UnauthenticatedSignupTravellerRoute
  UnauthenticatedSignupIndexRoute: typeof UnauthenticatedSignupIndexRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedSigninRoute: UnauthenticatedSigninRoute,
  UnauthenticatedSignupGuideRoute: UnauthenticatedSignupGuideRoute,
  UnauthenticatedSignupTravellerRoute: UnauthenticatedSignupTravellerRoute,
  UnauthenticatedSignupIndexRoute: UnauthenticatedSignupIndexRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
