name: Update Shared Package Version

on:
  push:
    paths:
      - 'shared/package.json'
    branches:
      - main

jobs:
  update-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get shared package version
        id: get-version
        run: |
          SHARED_VERSION=$(node -p "require('./shared/package.json').version")
          echo "version=$SHARED_VERSION" >> $GITHUB_OUTPUT

      - name: Update service package.json files
        run: |
          for service in services/*/; do
            if [ -f "$service/package.json" ]; then
              npx json -I -f "$service/package.json" -e "this.dependencies['@rapid-guide-io/shared']='${{ steps.get-version.outputs.version }}'"
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update @rapid-guide-io/shared to version ${{ steps.get-version.outputs.version }}"
          title: "chore: update shared package version to ${{ steps.get-version.outputs.version }}"
          body: |
            This PR updates the @rapid-guide-io/shared package version to ${{ steps.get-version.outputs.version }} in all services.
            
            Changes were triggered by an update to shared/package.json
          branch: update-shared-version
          base: main